name: .NET Framework Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Используем Windows, так как .NET Framework не поддерживается на Linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Framework Developer Pack
        run: |
          choco install dotnetfx -y
          choco install dotnetfx-devpack -y
          choco install windows-sdk-7.1 -y

      - name: Restore dependencies
        run: nuget restore

      - name: Build project
        run: msbuild /p:Configuration=Release

      - name: Run tests
        run: vstest.console.exe **\*.Tests.dll
