name: .NET Framework Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build project
        run: msbuild /p:Configuration=Release

      - name: Run tests
        run: |
          $vswhere = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
          $vstestPath = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools -property installationPath
          $vstestConsole = "$vstestPath\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe"
          & $vstestConsole **\*.Tests.dll
        shell: pwsh
